### ISSUE TITLE
NullReferenceException after loading the model

### ISSUE THREAD

**Issue by LuisAverhoff** [accord-net/framework#1030]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

Hey I recently started using this framework and my goal as of late has been to use this framework for gesture recognition using the leap motion V2.3.1 Skeletal Tracking to get the raw data of the user hands and some type of machine learning algorithm to accompany it. All of this is to be done in unity 5.6.2f1. 

With that said, the problem that I'm having is that everytime I do ```int gesureIndex = kNNClassifier.Decide(distanceVector);```after loading the model like this `return 
Serializer.Load<KNearestNeighbors<double[]>>(modelPath);`, I get a NullReferenceException and I don't know if there is something that I'm forgetting to initialize inside the model class(. Most of the values in the KNNClassifier class like the k, NumberOfInputs etc all return their correct values when I log them after loading the model. Even the object itself is not null after loading the model. The stack trace ends at KNearestNeighbour.GetNearestIndices(). So there must be something in that function that didn't get initialized after loading the model. What might that be?

The modules that I'm using is Accord, Accord.MachineLearning, Accord.Math and Accord.Statistics and the dll that each of them have is net35 - unity full v3.5 and of course the target framework that visual studio is using is Unity 3.5 net full base class libraries. I hope this helps you.

Here is my entire classifier class along with the local database file that holds all of my training data.

```C#
using System.Collections.Generic;
using Accord.MachineLearning;
using UnityEngine;
using Accord.Math.Distances;
using Accord.IO;
using System.IO;

public class Classifier : MonoBehaviour
{
    [SerializeField]
    private DataService dataService;

    [SerializeField]
    private int neighbours;

    public readonly static string modelPath = @"Assets/StreamingAssets/Models/GestureModel.bin";

    private KNearestNeighbors<double[]> kNNClassifier;

    [SerializeField]
    private bool isSavingModel = true;

    private Dictionary<string, int> gestures;

    private double[][] inputs;
    private int[] outputs;

    private void Start()
    {
        List<FeatureVector> featureVectors = dataService.getAllFeatureVectors();

        gestures = new Dictionary<string, int>();
        createGestureDictionary(featureVectors);

        if (File.Exists(modelPath))
        {
            kNNClassifier = loadModel();
        }
        else
        {
            train(featureVectors);
        }
    }

    private void createGestureDictionary(List<FeatureVector> featureVectors)
    {
        int gestureLabel = 0;

        foreach (FeatureVector featureVector in featureVectors)
        {
            if(!gestures.ContainsKey(featureVector.Gesture))
            {
                gestures.Add(featureVector.Gesture, gestureLabel);
                gestureLabel++;
            }
        }
    }

    private void train(List<FeatureVector> featureVectors)
    {
        kNNClassifier = new KNearestNeighbors<double[]>(k: neighbours, distance: new Euclidean());

        inputs = new double[featureVectors.Count][];
        outputs = new int[featureVectors.Count];

        createInputsAndOutputs(featureVectors);

        kNNClassifier.Learn(inputs, outputs);
    }

    private void createInputsAndOutputs(List<FeatureVector> featureVectors)
    {
        for (int i = 0; i < featureVectors.Count; i++)
        {
            inputs[i] = featureVectors[i].createDistanceVector();
            outputs[i] = gestures[featureVectors[i].Gesture];
        }
    }

    public string classifyGesture(double [] distanceVector)
    {
        int gesureIndex = kNNClassifier.Decide(distanceVector);

        foreach (KeyValuePair<string, int> pair in gestures)
            if (gesureIndex.Equals(pair.Value)) return pair.Key;

        return "Unknown Gesture";
    }

    public void saveModel()
    {
        Serializer.Save(kNNClassifier, modelPath);
    }

    public KNearestNeighbors<double[]> loadModel()
    {
        return Serializer.Load<KNearestNeighbors<double[]>>(modelPath);
    }

    private void OnApplicationQuit()
    {
        if (isSavingModel)
            saveModel();
    }
}
```

[Gesture_Data.zip](https://github.com/accord-net/framework/files/1463480/Gesture_Data.zip)

**Comment by LuisAverhoff** [comment]
I think I finally found the issue as to why this is happening. What is not getting initialized is this `double[] d = this.distances.Value;`. This only gets initialized after calling the learned method and it is non-serialized which means it doesn't get saved after calling the save serializer method. So does this means that I'm going to have train the model every time regardless if I save it? Is there any way I can initialize that array because the model did save the correct number of inputs ?

**Comment by LuisAverhoff** [comment]
So I solved my issue by removing the type double [] and just leaving it as KNearestNeighbors. This did bring up another issue with load and saving the model in which case I'll open it up as a separate issue.

**Comment by cesarsouza** [comment]
Hi @LuisAverhoff,

Thanks for opening the issue, I hadn't noticed it before as it had been closed. I've just committed a fix to the development branch.

Regards,
Cesar

**Comment by sharpwood** [comment]
This problem still exists in versions 3.8.0 and 3.8.2-alpha @cesarsouza
