### ISSUE TITLE
KNearestNeighbors can be serialized in v3.8.0 but can not be loaded

### ISSUE THREAD

**Issue by minhtdhktqs** [accord-net/framework#976]
- [x] bug report

my code in VB.net
Save model: 
Serializer.Save(k_n_n, Path.Combine(Application.StartupPath + "\Models\", "knn.bin"))+ "\Models\", "knn.bin"))
and load model:
 Serializer.Load(Path.Combine(Application.StartupPath + "\Models\", "knn.bin"), k_n_n)
but I cant use this model after load from file.
I get an Error in here:
Dim predicted As Integer = k_n_n.Decide(input)
An unhandled exception of type 'System.NullReferenceException' occurred in Accord.MachineLearning.dll
Additional information: Object reference not set to an instance of an object.

Can u check this error and fix it ?
thanks u.

**Comment by cesarsouza** [comment]
Hi @minhtdhktqs,

Thanks for opening the issue! However, I couldn't manage to reproduce it. Can you please let me know how you are creating your model? Are you using any custom distance function with it?

Regards,
Cesar

**Comment by minhtdhktqs** [comment]
Thanks for reply.
I trained my model by this code:
 Dim k_n_n As KNearestNeighbors
 Dim knn = New KNearestNeighbors() With {
            .K = 3
            .Distance = New Euclidean()
        }
  k_n_n = knn.Learn(inputs, outputs)

After that, I saved this model.
Save model:
Serializer.Save(k_n_n, Path.Combine(Application.StartupPath + "\Models", "knn.bin"))+ "\Models", "knn.bin"))
and load model:
Serializer.Load(Path.Combine(Application.StartupPath + "\Models", "knn.bin"), k_n_n)
but I cant use this model after load from file. I get an Error in here:
Dim predicted As Integer = k_n_n.Decide(input)
An unhandled exception of type 'System.NullReferenceException' occurred in Accord.MachineLearning.dll
Additional information: Object reference not set to an instance of an object.

If I don't load it from file and use directly after train model, it run ok and return result.

**Comment by cesarsouza** [comment]
Hi @minhtdhktqs, 

I am afraid I still couldn't reproduce it. Which version of .NET are you using? Are you using .NET Framework or .NET Core/Standard?

If it is possible, would you mind attaching a small project reproducing the issue to this thread?

Regards,
Cesar

**Comment by minhtdhktqs** [comment]
I fixed it.
I add this code:
Dim k_n_n = New KNearestNeighbors() With {
.K = 3
.Distance = New Euclidean()
}
before load model from file.
Serializer.Load(Path.Combine(Application.StartupPath + "\Models", "knn.bin"), k_n_n)

**Comment by minhtdhktqs** [comment]
thanks for your help

**Comment by sharpwood** [comment]
@cesarsouza This problem still exists in versions 3.8.0 and 3.8.2-alpha
